### ISSUE TITLE
Standard notation error when formatting eee5.31e16

### ISSUE THREAD

**Issue by cloudytheconqueror** [MathCookie17/Eternal-Notations#8]
```
EternalNotations.Presets.Standard.format(new Decimal('eee5.31e16'))
eternal_notations.js:4064 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at StandardNotation.calcLayer3 (eternal_notations.js:4064:37)
    at StandardNotation.calcLayer2 (eternal_notations.js:3982:32)
    at StandardNotation.formatDecimal (eternal_notations.js:3927:33)
    at StandardNotation.format (eternal_notations.js:1829:85)
    at <anonymous>:1:35
```
Error occurs with dialect 0 and 2. Error also happens with eee5.31e19 and eee5.34e16.

**Comment by MathCookie17** [comment]
Gosh darned e15 to e16 imprecision. I think most of the bugs that have slipped through and been found post-release are somehow related to imprecision in numbers close to 9e15.
